const express=require('express')
const itemsController=require('../controllers/itemsController')
const upload = require('../middleware/fileupload')
const protect = require('../middleware/AuthMiddleware')
const router=express.Router()
router.get('/getallitems',itemsController.getAllItems)
router.post('/add-item',protect,upload.single('image'),itemsController.addnewitems)
router.get('/edit/:_id',protect,itemsController.getedititems)
router.post('/update',protect,upload.single('image'),itemsController.postupdateitems)
router.post('/deleteitem/:_id',protect,itemsController.postdeleteitems)
module.exports=router
